### ISSUE TITLE
Checklist for 0.0.5

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#43]
- [x] Refresh tutorials content.
- [x] Find a way to fix painting the Sankey webmap example.
- [x] Get the documentation into a stable state.
- [ ] Vacuum down repo size.
- [ ] Clean out a feasible chunk of the other various issues in the bug tracker.
